import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

// Query plan for all four buildable KPIs comes directly from
// app/docs/kpi-reporting-design.md (Milestone 1 deliverable) — this service
// doesn't invent new definitions, it implements exactly what that doc
// specified. KPI 5 (member activity/engagement) is deliberately not
// implemented here — that doc's own recommendation was "don't guess at
// this one," since "engagement" needs a client clarification first.
@Injectable()
export class ReportsService {
  constructor(private readonly prisma: PrismaService) {}

  // KPI 1: total members. "Total" is ambiguous (all rows vs. ACTIVE only —
  // flagged in the design doc as worth confirming), so this returns the full
  // breakdown by status rather than picking one interpretation silently; the
  // frontend highlights ACTIVE as the headline figure while still showing
  // the others, so nothing is hidden behind a guess.
  async getMemberTotals() {
    const rows = await this.prisma.member.groupBy({
      by: ['membershipStatus'],
      _count: true,
    });
    return {
      byStatus: Object.fromEntries(
        rows.map((r) => [r.membershipStatus, r._count]),
      ),
      total: rows.reduce((sum, r) => sum + r._count, 0),
    };
  }

  // KPI 2: Founding/Annual/Newsletter(/Mongolia) breakdown. Grouped by
  // whatever tiers actually exist (not hardcoded to the original 3, per the
  // design doc's own note about the later-added MONGOLIA tier), plus a
  // separate isFoundingMember=true count — the design doc flags this as
  // likely more meaningful than a raw membershipTier='FOUNDING' count, since
  // Founding status is a permanent flag independent of current tier.
  async getTierBreakdown() {
    const rows = await this.prisma.member.groupBy({
      by: ['membershipTier'],
      _count: true,
    });
    const foundingMemberCount = await this.prisma.member.count({
      where: { isFoundingMember: true },
    });
    return {
      byTier: Object.fromEntries(rows.map((r) => [r.membershipTier, r._count])),
      foundingMemberCount,
    };
  }

  // KPI 3: new members per period. Buckets by real Member.createdAt values,
  // in JS rather than a raw SQL date_trunc — this dataset is small enough
  // that fetching timestamps in the requested window and bucketing them
  // client-side (server-side here, "client" of the DB) is simpler and avoids
  // raw SQL for what's ultimately a small, bounded query. Always returns
  // exactly `periods` buckets, oldest first, including zero-count buckets —
  // a real gap in signups is a real data point, not something to omit.
  async getNewMembersByPeriod(period: 'week' | 'month', periods: number) {
    const bucketStarts = buildBucketStarts(period, periods);
    const earliestStart = bucketStarts[0];

    const members = await this.prisma.member.findMany({
      where: { createdAt: { gte: earliestStart } },
      select: { createdAt: true },
    });

    const counts = new Map<string, number>(
      bucketStarts.map((d) => [d.toISOString(), 0]),
    );
    for (const member of members) {
      const bucketKey = bucketStartFor(member.createdAt, period, bucketStarts);
      if (bucketKey) {
        counts.set(bucketKey, (counts.get(bucketKey) ?? 0) + 1);
      }
    }

    return bucketStarts.map((d) => ({
      periodStart: d.toISOString(),
      count: counts.get(d.toISOString()) ?? 0,
    }));
  }

  // KPI 4: sales/orders generated by members. Summed per currency rather
  // than combined into one figure — MemberOrderCache.currency is per-order,
  // and silently adding amounts across different currencies would produce a
  // meaningless total if the store ever has more than one. Legitimately
  // returns zero/empty until the order-sync webhook is registered against
  // the live store (see PROJECT_TRACKER.md Section 0) — an accurate
  // reflection of real state, not a bug.
  async getOrderTotals(from?: Date, to?: Date) {
    const rows = await this.prisma.memberOrderCache.groupBy({
      by: ['currency'],
      where: from || to ? { orderDate: { gte: from, lte: to } } : undefined,
      _sum: { totalAmount: true },
      _count: true,
    });
    return rows.map((r) => ({
      currency: r.currency,
      totalAmount: r._sum.totalAmount?.toString() ?? '0',
      orderCount: r._count,
    }));
  }
}

function buildBucketStarts(period: 'week' | 'month', periods: number): Date[] {
  const now = new Date();
  const starts: Date[] = [];
  for (let i = periods - 1; i >= 0; i--) {
    starts.push(
      period === 'week'
        ? startOfWeekOffset(now, i)
        : startOfMonthOffset(now, i),
    );
  }
  return starts;
}

// Monday-start week, UTC-based to keep bucketing deterministic regardless of
// server timezone.
function startOfWeekOffset(now: Date, weeksAgo: number): Date {
  const d = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()),
  );
  const day = d.getUTCDay();
  const diffToMonday = (day + 6) % 7;
  d.setUTCDate(d.getUTCDate() - diffToMonday - weeksAgo * 7);
  return d;
}

function startOfMonthOffset(now: Date, monthsAgo: number): Date {
  return new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - monthsAgo, 1),
  );
}

function bucketStartFor(
  createdAt: Date,
  period: 'week' | 'month',
  bucketStarts: Date[],
): string | null {
  // Find the latest bucket start that's <= createdAt — bucketStarts is
  // ascending, so scan from the end.
  for (let i = bucketStarts.length - 1; i >= 0; i--) {
    if (bucketStarts[i].getTime() <= createdAt.getTime()) {
      return bucketStarts[i].toISOString();
    }
  }
  return null;
}
